# Use something that's not 'ruby' so we don't set up things like
# RVM/bundler/ruby and whatnot.
language: c
sudo: false

script:
  - ./test.sh
  # Ensure no lines are indented using spaces.
  - test $(git grep '	' -- src/multirust | wc -l) -eq 0

branches:
  only:
    - master
