# Use something that's not 'ruby' so we don't set up things like
# RVM/bundler/ruby and whatnot.
language: c
sudo: false

script:
  - ./test.sh
  # Ensure no files are indented using tabs.
  - test $(git grep -l '	' | wc -l) -eq 4

branches:
  only:
    - master
